### ISSUE TITLE
VEuPathDB / CORRAL not working

### ISSUE THREAD

**Issue by ailtonpcf** [wbazant/eukprot-alignments-nextflow#4] opened 2023-05-19 12:23 UTC
To whom it may concern,

Thanks for developing a nice tool to help studying eukaryotes from shotgun data. My issue is being open here because VEuPathDB / CORRAL doesn't have an issue channel. I've been trying to run CORRAL with the following config:

`
process {
  executor = 'slurm'
  queue = 'standard'
  time = '72h'  // Set the maximum time required for each task
  memory = '50GB'  // Set the maximum memory required for each task
}

singularity {
   enabled = true
}

params {
  alignmentStatsCommand = "samtools stats"
  libraryLayout = "paired"
  downloadMethod = "local"
  markerToTaxonPath = "$launchDir/data/marker-to-taxon-id.tsv"
  bowtie2Command = "bowtie2 --omit-sec-seq --no-discordant --no-unal -a"
  summarizeAlignmentsCommand = 'marker_alignments --min-read-query-length 60 --min-taxon-num-markers 2 --min-taxon-num-reads 2 --min-taxon-better-marker-cluster-averages-ratio 1.01 --threshold-avg-match-identity-to-call-known-taxon 0.97  --threshold-num-taxa-to-call-unknown-taxon 1000 --threshold-num-markers-to-call-unknown-taxon 1000     --threshold-num-reads-to-call-unknown-taxon 1000'
  summaryFormat = "matrix"
  summaryColumn = "cpm"
}
process {
  container = "veupathdb/corral:latest"
}
`
My HPC structure rely on slurm and singularity. However, CORRAL doesn't want to run with singularity : "Cannot enable more than one container engine -- Choose either one of: docker, singularity"

After supplying:

process {
  containerOptions {
    docker.enabled = false
    singularity.enabled = true
  }
}

The job finishes before real execution and has no error message:

`
ate              = Fri May 19 14:16:33 CEST 2023
Hostname          = node069
Working Directory = /home/qi47rin/proj/02-compost-microbes/src/08-corral

Number of Nodes Allocated      = 1
Number of Tasks Allocated      = 1
Number of Cores/Task Allocated = 1

N E X T F L O W  ~  version 22.10.0
Launching `https://github.com/VEuPathDB/CORRAL` [magical_waddington] DSL2 - revision: da2fa85ff0 [main]
[-        ] process > local:bowtie2             -
[-        ] process > local:alignmentStats      -
[-        ] process > local:summarizeAlignments -
[-        ] process > local:makeTsv             -

[-        ] process > local:bowtie2             -
[-        ] process > local:alignmentStats      -
[-        ] process > local:summarizeAlignments -
[-        ] process > local:makeTsv             -

[-        ] process > local:bowtie2             -
[-        ] process > local:alignmentStats      -
[-        ] process > local:summarizeAlignments -
[-        ] process > local:makeTsv             -
`

Thanks for the support,
Ailton.

**Comment by wbazant** [comment] 2023-05-19 17:27
Hi, thanks for your interest in the tool! I don't work for VEuPathDB any more but if you want to reproduce their CORRAL runs or find out more about how they use the tool, the helpdesk (https://microbiomedb.org/mbio/app/contact-us ) is probably your best bet.

If you want to run the software, you could try this fork. `wbazant/CORRAL` accompanies the paper https://doi.org/10.1186/s40168-023-01505-1 , and doesn't have the container setup of `veupathdb/CORRAL` , but the bioinformatics bit is the same.

Also, 
```
 --threshold-num-taxa-to-call-unknown-taxon 1000 --threshold-num-markers-to-call-unknown-taxon 1000 --threshold-num-reads-to-call-unknown-taxon 1000
```
this will almost definitely not show you any results, try the original values - see the readme!

**Comment by wbazant** [comment] 2023-05-19 17:34
@ailtonpcf I'm closing the issue, since "I can't support VEuPathDB / CORRAL, you can go ask them, or run this tool" is formally the answer to it, but let me know how you get on, and if the installation instructions don't work for you, please let me know!

**Closed as completed by wbazant** 2023-05-19 17:34 UTC
